language: android
android:
  components:
    - extra
    - build-tools-23.0.1
    - build-tools-22.0.1
    - android-23
    - android-22
    - sys-img-x86-android-23
before_script:
  - git clone https://android.googlesource.com/platform/frameworks/volley library/volley
  - rm library/volley/src/test -r
  - mv library/volley-gradle/* library/volley/
